import React from 'react';
import type { Meta, StoryObj } from '@storybook/react-vite';
import '../../styles/tokens.css';
import '../../styles/fonts.css';
import '../../styles/dos-utilities.css';
import '../../styles/provenance.css';

/**
 * NOTE: this directory ships **no React component** of its own. Provenance
 * is a pure-CSS primitive — the canonical `[data-provenance="ai-draft"]`
 * attribute and the `[data-ai-block]` wrapper — that consumers wire up by
 * setting the HTML attribute themselves. The `AIText` component in
 * `components/AIText/` is the ergonomic React shortcut over the attribute.
 *
 * The story-only directory mirrors `src/components/Tokens/`, the existing
 * pattern for documentation-only design-system surfaces.
 */
const meta = {
  title: 'Design System/Content Provenance',
  parameters: {
    layout: 'padded',
    backgrounds: {
      default: 'dos',
      values: [
        { name: 'dos', value: '#020003' },
        { name: 'light', value: '#FFE8A8' },
      ],
    },
    docs: {
      description: {
        component:
          'Visual primitive for AI-drafted prose. Consumers emit `data-provenance="ai-draft"` on `<p>` / `<li>` / `<blockquote>` elements (per-paragraph), or `data-ai-block` on a wrapper element (whole-section marking). Eidotter renders the magenta→white→cyan shimmer gradient on the text glyphs via `background-clip: text`. The diff machinery (`mark-provenance.mjs`) and explicit human-mark workflow live in consumer repos. See `plans/2026-05-02-001-feat-ai-content-provenance-marker-plan.md` (Phase 1) and the DMNC-946 evolution to the gradient visual.',
      },
    },
  },
} satisfies Meta;

export default meta;
type Story = StoryObj;

const proseWidth: React.CSSProperties = { maxWidth: '60ch' };

/**
 * Default: a single AI-drafted paragraph against the DOS dark backdrop.
 * The magenta→white→cyan gradient shimmers slowly across the glyphs.
 */
export const Default: Story = {
  render: () => (
    <div className="dos-page" style={proseWidth}>
      <p className="dos-body" data-provenance="ai-draft">
        This paragraph was generated by an AI workflow and has not yet been
        revised by a human author. The shimmering CGA gradient signals the
        text is still AI-baseline. Rewrite it in your own voice, then remove
        the `data-provenance="ai-draft"` attribute (or run the consumer's
        human-mark script) to settle it back to the default colour.
      </p>
    </div>
  ),
};

/**
 * Mixed-state page: AI-drafted alongside revised. This is what an
 * in-progress audit looks like — gradient on the still-AI passages,
 * default colour on the rewritten ones.
 */
export const MixedDraftAndRevised: Story = {
  render: () => (
    <div className="dos-page" style={proseWidth}>
      <p className="dos-caption">Revised paragraph (no attribute)</p>
      <p className="dos-body">
        I rewrote this paragraph end-to-end after the AI generated its first
        draft. It carries my voice now — the cadence, the diction, the
        opinions all came from me, not the model.
      </p>
      <p className="dos-caption" style={{ marginTop: '1.5rem' }}>
        AI-drafted paragraph (shimmering gradient)
      </p>
      <p className="dos-body" data-provenance="ai-draft">
        This paragraph is still in its original AI form. Beyond a few cosmetic
        edits I have not yet engaged with the substance — the framing is the
        model's, not mine. The gradient stays until I rewrite it.
      </p>
    </div>
  ),
};

/**
 * Light backdrop. The gradient endpoints (magenta + cyan) clear AA contrast
 * against any background, so the marker reads on both DOS dark and light hosts.
 */
export const OnLightBackdrop: Story = {
  parameters: {
    backgrounds: { default: 'light' },
  },
  render: () => (
    <div className="dos-body" style={proseWidth}>
      <p data-provenance="ai-draft">
        AI-drafted prose on a light backdrop — the magenta→white→cyan gradient
        still reads on a cream background. Validates that the marker works
        outside the default DOS dark canvas.
      </p>
    </div>
  ),
};

/**
 * Variants across paragraph types: `<p>`, `<li>`, prose `<blockquote>`.
 * The selector applies to any prose element carrying the attribute.
 */
export const Variants: Story = {
  render: () => (
    <div className="dos-page" style={proseWidth}>
      <p className="dos-caption">&lt;p&gt; element</p>
      <p className="dos-body" data-provenance="ai-draft">
        A standard prose paragraph rendered with the shimmering CGA gradient.
      </p>
      <p className="dos-caption" style={{ marginTop: '1.5rem' }}>
        &lt;li&gt; in an unordered list
      </p>
      <ul className="dos-body">
        <li>This list item is human-authored.</li>
        <li data-provenance="ai-draft">
          This list item is still AI-drafted and needs revision.
        </li>
        <li>This one is also human-authored.</li>
      </ul>
      <p className="dos-caption" style={{ marginTop: '1.5rem' }}>
        Prose &lt;blockquote&gt;
      </p>
      <blockquote
        className="dos-body"
        data-provenance="ai-draft"
        style={{ borderLeft: '2px solid currentColor', paddingLeft: '1em', margin: 0 }}
      >
        AI-drafted pull quote — when prose blockquotes carry generated text,
        they pick up the gradient just like regular paragraphs.
      </blockquote>
    </div>
  ),
};

/**
 * `data-ai-block` wrapper — whole-section marking. The attribute on the
 * wrapper paints every prose descendant (h1-h6, p, li, blockquote, strong,
 * em, code). Used by non-MDX surfaces where stamping individual elements
 * is impractical.
 */
export const BlockModeWrapper: Story = {
  parameters: {
    docs: {
      description: {
        story:
          'Apply `data-ai-block` to any container element (`<article>`, `<main>`, `<section>`) and every prose descendant inside picks up the gradient. Non-prose descendants (buttons, swatches, terminal previews, etc.) stay untouched because the rule only targets text elements explicitly.',
      },
    },
  },
  render: () => (
    <article className="dos-page" style={proseWidth} data-ai-block>
      <h2 className="dos-body" style={{ fontSize: '1.5em', marginBottom: '0.5em' }}>
        A whole-section AI-marked heading
      </h2>
      <p className="dos-body">
        Every prose element inside this article inherits the gradient via the
        `[data-ai-block] :is(h1, h2, …)` selector.
      </p>
      <p className="dos-body">
        Two paragraphs, both lit. The author can opt-out specific descendants
        with `data-ai-skip="true"` — see the next story.
      </p>
    </article>
  ),
};

/**
 * `data-ai-skip="true"` opt-out. Any descendant of a block-mode wrapper
 * tagged with `data-ai-skip="true"` reverts to its inherited colour.
 * Works both inside `data-ai-block` AND alongside bare
 * `data-provenance="ai-draft"` spans.
 */
export const OptOut: Story = {
  parameters: {
    docs: {
      description: {
        story:
          '`data-ai-skip="true"` is the escape hatch. Use it on a child element when an entire region is AI-marked but a specific subtree should stay un-marked — e.g., quoted attribution, verbatim user input, or styled non-prose components inside an article wrapper.',
      },
    },
  },
  render: () => (
    <article className="dos-page" style={proseWidth} data-ai-block>
      <p className="dos-body">
        Normal AI-marked paragraph — gradient applied.
      </p>
      <div data-ai-skip="true">
        <p className="dos-body">
          This paragraph is inside a `data-ai-skip="true"` wrapper. The
          gradient is suppressed; the text renders in the default inherited
          colour.
        </p>
      </div>
      <p className="dos-body">
        Back to AI-marked — the opt-out scope ended at the wrapper.
      </p>
    </article>
  ),
};

/**
 * `data-ai-skip="true"` nested INSIDE a `data-provenance="ai-draft"` paragraph.
 * Regression guard for DMNC-1314: the skip span must revert to readable body
 * text even though its ancestor paragraph paints transparent glyphs. This is
 * exactly where an InlineExpand content span lands when its trigger word sits
 * in an ai-draft paragraph.
 */
export const SkipInsideProvenance: Story = {
  parameters: {
    docs: {
      description: {
        story:
          'A `data-ai-skip="true"` span nested inside an `ai-draft` paragraph reverts to the default body colour, while the surrounding gradient-marked prose keeps its marker. Without the dedicated reset, the nested skip would inherit the ancestor’s transparent text and vanish. Verify in BOTH the dos (dark) and light backgrounds.',
      },
    },
  },
  render: () => (
    <div className="dos-page" style={proseWidth}>
      <p className="dos-body" data-provenance="ai-draft">
        This sentence carries the AI-draft gradient marker, but{' '}
        <span data-ai-skip="true">
          this nested span opts out and must stay readable
        </span>{' '}
        while the marked text resumes after it.
      </p>
    </div>
  ),
};

/**
 * Reduced-motion preference. Toggle the OS / browser preference to verify
 * the shimmer animation actually pauses — Storybook can't fake the media
 * query.
 */
export const ReducedMotion: Story = {
  parameters: {
    docs: {
      description: {
        story:
          'Under `prefers-reduced-motion: reduce` the shimmer animation is disabled; the gradient itself stays. Storybook cannot simulate the media query — toggle it via OS settings or DevTools to verify the real effect.',
      },
    },
  },
  render: () => (
    <div className="dos-page" style={proseWidth}>
      <p className="dos-body" data-provenance="ai-draft">
        With <code>prefers-reduced-motion: reduce</code> set, the gradient
        sweep across this text stops; the colours stay in place. The AI-draft
        signal isn&rsquo;t lost — only the motion is.
      </p>
    </div>
  ),
};

/**
 * Wall of pink: 6 consecutive AI-drafted paragraphs.
 *
 * Sanity check on fatigue tolerance: a freshly stamped post is 100%
 * gradient. Does it still read as urgent at scale, or has the eye glazed
 * over by paragraph 4? The shimmer is calibrated at 12s `ease-in-out`
 * specifically to keep the signal active without becoming distracting.
 */
export const WallOfMarkedProse: Story = {
  parameters: {
    docs: {
      description: {
        story:
          'Six consecutive AI-drafted paragraphs — what a freshly stamped devjournal entry looks like before any revision. If this still reads as "to-do list", the calibration is right. If it has become wallpaper, the shimmer or threshold needs tuning.',
      },
    },
  },
  render: () => (
    <div className="dos-page" style={proseWidth}>
      <p className="dos-caption">Freshly stamped entry — every paragraph still AI-baseline</p>
      {[
        'The first paragraph of any AI-drafted devjournal entry sets the frame: model output, not yet engaged with by a human. This is what generation looks like before a single edit lands.',
        'By the second paragraph the gradient has accumulated. The reader sees a wall of saturated colour and registers it as a deliberate visual state — not an accident, not a decoration.',
        'By the third, the question is whether the eye has acclimated. Wallpaper effect: when an alarm rings continuously, you stop hearing it. The shimmer-fatigue risk is what this story exists to surface.',
        'Halfway through. If the gradient has become background, the system is failing its job — the marker has become decoration. If it still reads as urgent, the threshold and intensity are calibrated correctly.',
        'The fifth paragraph is where most readers either start skimming or actively engage with the revision task. Either response is fine; the goal is that the prose is unmissable, not unreadable.',
        'By the sixth and final paragraph, the cumulative weight of unowned text should feel uncomfortable. The gradient is the to-do list. Discomfort here is the design working as intended.',
      ].map((text, i) => (
        <p key={i} className="dos-body" data-provenance="ai-draft" style={{ marginTop: i > 0 ? '1rem' : 0 }}>
          {text}
        </p>
      ))}
    </div>
  ),
};
