import React from 'react';
import type { Meta, StoryObj } from '@storybook/react-vite';
import '../../styles/tokens.css';
import '../../styles/fonts.css';
import '../../styles/dos-utilities.css';
import '../../styles/provenance.css';

/**
 * NOTE: this directory ships **no React component**. Provenance is a
 * pure-CSS primitive — a token + a `[data-provenance="ai-draft"]` selector
 * — that consumers wire up by setting the HTML attribute themselves.
 *
 * The story-only directory mirrors `src/components/Tokens/`, the existing
 * pattern for documentation-only design-system surfaces. Phase 2 (devjournal
 * integration) and phase 5 (public surfaces) consume the primitive without
 * adding component code here.
 */
const meta = {
  title: 'Design System/Content Provenance',
  parameters: {
    layout: 'padded',
    backgrounds: {
      default: 'dos',
      values: [
        { name: 'dos', value: '#020003' },
        { name: 'light', value: '#FFE8A8' },
      ],
    },
    docs: {
      description: {
        component:
          'Visual primitive for AI-drafted prose. Render-time consumers (devjournal, public-site SSGs) emit `data-provenance="ai-draft"` on prose elements after running their per-paragraph diff against the AI baseline. Eidotter ships the visual hook only — the diff machinery lives downstream. See `plans/2026-05-02-001-feat-ai-content-provenance-marker-plan.md`.',
      },
    },
  },
} satisfies Meta;

export default meta;
type Story = StoryObj;

const proseWidth: React.CSSProperties = { maxWidth: '60ch' };

/**
 * Default: a single AI-drafted paragraph against the DOS dark backdrop.
 * The hot pink reads as a clear "fix me" marker.
 */
export const Default: Story = {
  render: () => (
    <div className="dos-page" style={proseWidth}>
      <p className="dos-body" data-provenance="ai-draft">
        This paragraph was generated by an AI workflow and has not yet been
        revised by a human author. The Signalnoise hot pink signals
        unambiguously that the prose is provisional — your job is to revise it
        into your own voice until the colour shifts back to amber.
      </p>
    </div>
  ),
};

/**
 * AI-drafted paragraph next to a revised one. Demonstrates how mixed-state
 * pages read in the wild — pink for to-do, amber for owned content.
 */
export const MixedDraftAndRevised: Story = {
  render: () => (
    <div className="dos-page" style={proseWidth}>
      <p className="dos-caption">Revised paragraph (default amber)</p>
      <p className="dos-body">
        I rewrote this paragraph end-to-end after the AI generated its first
        draft. It carries my voice now — the cadence, the diction, the
        opinions all came from me, not the model.
      </p>
      <p className="dos-caption" style={{ marginTop: '1.5rem' }}>
        AI-drafted paragraph (Signalnoise pink)
      </p>
      <p className="dos-body" data-provenance="ai-draft">
        This paragraph is still in its original AI form. Beyond a few cosmetic
        edits I have not yet engaged with the substance — the framing is the
        model's, not mine. The pink stays until I do the work.
      </p>
    </div>
  ),
};

/**
 * Same content, light backdrop. Verifies the marker still reads against
 * non-DOS hosts (e.g. printed page, light-themed embed).
 */
export const OnLightBackdrop: Story = {
  parameters: {
    backgrounds: { default: 'light' },
  },
  render: () => (
    <div className="dos-body" style={proseWidth}>
      <p data-provenance="ai-draft">
        AI-drafted prose on a light backdrop — Signalnoise pink still punches
        through against amber-on-cream. This validates that the marker works
        outside the default DOS dark canvas.
      </p>
    </div>
  ),
};

/**
 * Variants across paragraph types: `<p>`, `<li>`, prose `<blockquote>`.
 * The selector applies to any element carrying the attribute, not just
 * paragraphs — useful for marking AI-drafted list items or pull quotes.
 *
 * Note the `<a>` tag: links keep their own colour by deliberate design
 * (link affordance trumps the AI-draft signal — see provenance.css comment).
 */
export const Variants: Story = {
  render: () => (
    <div className="dos-page" style={proseWidth}>
      <p className="dos-caption">&lt;p&gt; element</p>
      <p className="dos-body" data-provenance="ai-draft">
        A standard prose paragraph rendered in Signalnoise pink — including a
        link that keeps its own affordance colour.
      </p>
      <p className="dos-caption" style={{ marginTop: '1.5rem' }}>
        &lt;li&gt; in an unordered list
      </p>
      <ul className="dos-body">
        <li>This list item is human-authored.</li>
        <li data-provenance="ai-draft">
          This list item is still AI-drafted and needs revision.
        </li>
        <li>This one is also human-authored.</li>
      </ul>
      <p className="dos-caption" style={{ marginTop: '1.5rem' }}>
        Prose &lt;blockquote&gt;
      </p>
      <blockquote
        className="dos-body"
        data-provenance="ai-draft"
        style={{ borderLeft: '2px solid currentColor', paddingLeft: '1em', margin: 0 }}
      >
        AI-drafted pull quote — when prose blockquotes carry generated text,
        they pink up just like regular paragraphs.
      </blockquote>
    </div>
  ),
};

/**
 * Wall of pink: 6 consecutive AI-drafted paragraphs.
 *
 * Validates fatigue tolerance — the plan's biggest risk is that a freshly
 * generated entry is 100% pink and the signal becomes wallpaper. This story
 * is the visual sanity check: does the pink still read as urgent at scale,
 * or has the eye glazed over by paragraph 4? If it glazes, the threshold
 * (currently 40% Levenshtein) needs to drop or the pink needs another
 * dimension (icon, badge, weight) to stay legible.
 */
export const WallOfPink: Story = {
  parameters: {
    docs: {
      description: {
        story:
          "Six consecutive AI-drafted paragraphs — what a freshly generated devjournal entry looks like before any revision. If this reads as oppressive rather than 'urgent to-do', the pink-fatigue risk in the plan is real and the threshold or treatment needs tuning.",
      },
    },
  },
  render: () => (
    <div className="dos-page" style={proseWidth}>
      <p className="dos-caption">Freshly generated entry — every paragraph is AI-drafted</p>
      {[
        'The first paragraph of any AI-drafted devjournal entry sets the frame: model output, not yet engaged with by a human. This is what generation looks like before a single edit lands.',
        'By the second paragraph the pink has accumulated. The reader sees a wall of saturated colour and registers it as a deliberate visual state — not an accident, not a decoration.',
        'By the third, the question is whether the eye has acclimated. Wallpaper effect: when an alarm rings continuously, you stop hearing it. Pink-fatigue is the design risk this story exists to surface.',
        'Halfway through. If the pink has become background, the system is failing its job — the marker has become decoration. If it still reads as urgent, the threshold and intensity are calibrated correctly.',
        'The fifth paragraph is where most readers either start skimming or actively engage with the revision task. Either response is fine; the goal is that the prose is unmissable, not unreadable.',
        'By the sixth and final paragraph, the cumulative weight of unowned text should feel uncomfortable. The pink is the to-do list. Discomfort here is the design working as intended.',
      ].map((text, i) => (
        <p key={i} className="dos-body" data-provenance="ai-draft" style={{ marginTop: i > 0 ? '1rem' : 0 }}>
          {text}
        </p>
      ))}
    </div>
  ),
};

/**
 * High-contrast simulation. Phosphor halo neutralized, colour preserved.
 * Toggle the OS / browser high-contrast setting to validate the actual
 * `prefers-contrast: high` media query — Storybook can't fake it.
 */
export const HighContrastNeutralizesGlow: Story = {
  parameters: {
    docs: {
      description: {
        story:
          'When `prefers-contrast: high` is set, the phosphor `text-shadow` halo is removed but the colour stays. Storybook cannot simulate the media query — toggle it via OS / DevTools to see the real effect.',
      },
    },
  },
  render: () => (
    <div className="dos-page" style={proseWidth}>
      <p className="dos-body" data-provenance="ai-draft">
        Under <code>prefers-contrast: high</code> the magenta phosphor halo
        around this text is dropped (CSS rule in <code>provenance.css</code>).
        The Signalnoise hot pink colour itself remains so the AI-draft signal
        isn't lost.
      </p>
    </div>
  ),
};
