/**
 * Contract tests for the shadcn/ui token shim (DMNC-922).
 *
 * `src/styles/shadcn.css` is generated by `scripts/generate-shadcn-shim.mjs`
 * (run in `npm run build-tokens`). It maps shadcn var names to eidotter's
 * semantic roles as HSL channels so a shadcn consumer's `hsl(var(...))` usages
 * consume eidotter's themeable palette. These tests pin the contract.
 */
import { existsSync, readFileSync } from 'fs';
import { resolve } from 'path';

const shimPath = resolve(__dirname, 'shadcn.css');
const css = readFileSync(shimPath, 'utf-8');

// HSL channel form shadcn consumes via `hsl(var(...))`, e.g. "41 100% 50%".
const HSL = /:\s*\d{1,3}\s+\d{1,3}%\s+\d{1,3}%\s*;/;

// The block scoped to `selector` (up to its closing brace).
function block(selector: string): string {
  const start = css.indexOf(selector);
  if (start === -1) return '';
  const open = css.indexOf('{', start);
  const close = css.indexOf('}', open);
  return css.slice(open, close);
}

describe('shadcn.css — shim contract', () => {
  const CORE = [
    'background', 'foreground', 'card', 'card-foreground', 'popover',
    'popover-foreground', 'primary', 'primary-foreground', 'secondary',
    'secondary-foreground', 'muted', 'muted-foreground', 'accent',
    'accent-foreground', 'destructive', 'destructive-foreground', 'border',
    'input', 'ring',
  ];

  it('exists and is the generated shim', () => {
    expect(existsSync(shimPath)).toBe(true);
    expect(css).toMatch(/GENERATED — do not edit/);
  });

  it.each(CORE)(':root defines --%s as HSL channels', (name) => {
    const root = block(':root');
    expect(root).toMatch(new RegExp(`--${name}${HSL.source}`));
  });

  it('every mapped var resolved (no leftover "unresolved" comments)', () => {
    expect(css).not.toMatch(/unresolved/);
  });

  it('emits a block per theme and re-themes ([data-theme="amber-mono"])', () => {
    const amber = block('[data-theme="amber-mono"]');
    expect(amber).not.toBe('');
    // amber-mono brand is phosphor amber #FFB000 = "41 100% 50%".
    expect(amber).toMatch(/--primary:\s*41 100% 50%/);
    // amber-mono foreground (text.primary → amber) differs from :root (lightGray).
    const rootFg = block(':root').match(/--foreground:\s*([^;]+);/)?.[1].trim();
    const amberFg = amber.match(/--foreground:\s*([^;]+);/)?.[1].trim();
    expect(amberFg).not.toEqual(rootFg);
  });

  it.each(['cga-amber', 'cga-mode4-p0', 'cga-mode4-p1', 'cga-mode5', 'light'])(
    'emits a [data-theme="%s"] block',
    (theme) => {
      expect(block(`[data-theme="${theme}"]`)).not.toBe('');
    },
  );

  it('is opt-in — NOT bundled into dist/eidotter.css', () => {
    const distPath = resolve(__dirname, '..', '..', 'dist', 'eidotter.css');
    if (!existsSync(distPath)) return; // dist only present after build
    const dist = readFileSync(distPath, 'utf-8');
    // The shadcn `--background` shim var must not leak into the main bundle.
    expect(dist).not.toMatch(/--background:\s*\d{1,3}\s+\d{1,3}%/);
  });
});
