import React from 'react';
import type { Meta, StoryObj } from '@storybook/react-vite';
import { AIText } from './AIText';
import '../../../styles/tokens.css';
import '../../../styles/fonts.css';
import '../../../styles/dos-utilities.css';
import '../../../styles/provenance.css';

/**
 * `<AIText>` is the inline React ergonomic shortcut over the canonical
 * `data-provenance="ai-draft"` attribute. The visual lives in
 * `provenance.css` and is shared with the per-paragraph diff pipeline.
 *
 * Use this when wrapping a single phrase or fragment inside otherwise-human
 * prose. For per-paragraph marking, prefer `<p data-provenance="ai-draft">`
 * directly so downstream diff tools can stamp / unwrap automatically.
 */
const meta = {
  title: 'Design System/AIText',
  component: AIText,
  parameters: {
    layout: 'padded',
    backgrounds: {
      default: 'dos',
      values: [
        { name: 'dos', value: '#020003' },
        { name: 'light', value: '#FFE8A8' },
      ],
    },
    docs: {
      description: {
        component:
          'Inline marker for AI-drafted prose. Renders a `<span>` with `data-provenance="ai-draft"`; eidotter\'s `provenance.css` paints it with the magenta→white→cyan shimmer gradient. Includes a screen-reader-only "AI-assisted:" prefix and a default `title` hover label.',
      },
    },
  },
  argTypes: {
    title: {
      control: 'text',
      description: 'Hover tooltip; defaults to "AI-assisted text — being rewritten"',
    },
    className: {
      control: 'text',
      description: 'Additional class names merged onto the wrapping span',
    },
  },
} satisfies Meta<typeof AIText>;

export default meta;
type Story = StoryObj<typeof AIText>;

const proseWidth: React.CSSProperties = { maxWidth: '60ch' };

/**
 * Default — one inline AI span inside an otherwise-human paragraph.
 */
export const Default: Story = {
  args: {
    children: 'this one phrase came from a model',
  },
  render: (args) => (
    <p className="dos-body" style={proseWidth}>
      Most of this sentence is mine, but <AIText {...args} />. The pink area
      is what I still need to rewrite.
    </p>
  ),
};

/**
 * Multiple inline AI spans in the same paragraph — typical mid-revision
 * state. As the author replaces phrases with their own voice, the marked
 * area shrinks visibly.
 */
export const MultipleInlineSpans: Story = {
  render: () => (
    <p className="dos-body" style={proseWidth}>
      I rewrote the opening. <AIText>This middle stretch is still the model&rsquo;s</AIText>
      , but the next sentence is mine. <AIText>And this final clause came back from a prompt</AIText>
      .
    </p>
  ),
};

/**
 * Custom hover label — override `title` to give readers context-specific
 * hint text on mouse-over.
 */
export const CustomHoverLabel: Story = {
  args: {
    children: 'this technical claim',
    title: 'Generated by GPT-4 — verify against the spec',
  },
  render: (args) => (
    <p className="dos-body" style={proseWidth}>
      We measured throughput at 12,000 req/s under the load profile, but{' '}
      <AIText {...args} /> hasn&rsquo;t been validated against the spec yet.
    </p>
  ),
};

/**
 * On a light background — the gradient still reads thanks to the white
 * midpoint stop in the linear-gradient.
 */
export const OnLightBackdrop: Story = {
  parameters: { backgrounds: { default: 'light' } },
  args: { children: 'this fragment is AI' },
  render: (args) => (
    <p className="dos-body" style={proseWidth}>
      A paragraph on a light background, with{' '}
      <AIText {...args} /> marked inline. The shimmer still reads.
    </p>
  ),
};

/**
 * Inside a heading — the gradient applies to any element AIText wraps,
 * including non-paragraph hosts like headings or list items.
 */
export const InsideHeading: Story = {
  render: () => (
    <div style={proseWidth}>
      <h2 className="dos-body" style={{ fontSize: '1.5em' }}>
        How <AIText>I think about AI-content marking</AIText> right now
      </h2>
      <p className="dos-body">
        The heading above is part AI, part mine — the marked fragment shimmers
        with the same gradient as paragraph-level marks.
      </p>
    </div>
  ),
};
